# Generated by Django 3.1.2

from django.db import migrations, models
class Migration(migrations.Migration):
    initial = True
    dependencies =  [
        ]
    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True))
                ('name', models.CharField(max_length=200))
                ('visited', models.BooleanFielddefault=False))

            ]
        )
    ]